#!/bin/bash

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/..";pwd)"
cd "$PROJECT_ROOT"

if [[ "$#" -gt 0 ]] && [[ "$1" = "check" ]]; then
    # Check only

    echo "████████████████████████████   black   █████████████████████████████"
    poetry run black --check src/sudoku tests
    echo "████████████████████████████   ruff   █████████████████████████████"
    poetry run ruff check src
else
    # Reformat

    echo "████████████████████████████   black   █████████████████████████████"
    poetry run black src/sudoku tests
    echo "████████████████████████████   ruff   █████████████████████████████"
    poetry run ruff src
fi
