#!/bin/bash

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/..";pwd)"
cd "$PROJECT_ROOT"

echo "██████████████████████████████  mypy  ██████████████████████████████"
poetry run mypy src/sudoku tests
echo "██████████████████████████████ pylint ██████████████████████████████"
poetry run pylint src/sudoku tests
